### ISSUE TITLE
Multi-tenant kms_key

### ISSUE THREAD

**Issue by sshkarupa** [ankane/kms_encrypted#11]
Hey. I'm trying to implement encryption / decryption users' data for multi-tenant SaaS application. And I want to use different `kms_keys` for different tenant.  I need to generate key_id "on the fly" depending on a current domain, for example, like this: 

```ruby
has_kms_key key_id: "#{tenant}_kms_key"
```
When I do like this it doesn't work correctly. It caches the name of `the key_id` somehow. And after I switched the tenant it returns me the old name of the `kms_id`. Is it posible to use your gem in my use case?

**Comment by ankane** [comment]
Hey @sshkarupa, on master, you can now use a proc for the key id.

```ruby
has_kms_key key_id: -> { "#{tenant}_kms_key" } 
```

**Comment by sshkarupa** [comment]
@ankane Thanks
