### ISSUE TITLE
Undefined method `encrypted_value' for...

### ISSUE THREAD

**Issue by benbonnet** [ankane/kms_encrypted#14]
Quite unsure if it's me or because am using rails 6rc1, I've found it hard ot have it work as advertised; feels like something is not working

Having the following :

```
class CreateApiCredentials < ActiveRecord::Migration[6.0]
  def change
    create_table :api_credentials do |t|
      t.string :name
      t.text :encrypted_kms_key
      t.timestamps
    end
  end
end
```

```
class ApiCredential < ApplicationRecord
  has_kms_key
  attr_encrypted :value, key: :kms_key
end
```

While trying the following :

```
ApiCredential.create(name: 'demokey', value: 'demo_value')
```

I keep getting the following :

```
NoMethodError (undefined method `encrypted_value' for #<ApiCredential:0x00007fc2b5c22bb0>)
Did you mean?  encrypted_attributes
```

I hope that I haven't missed an obvious part; still i'd be glad to know if there wasn't anything to consider further

Using the 'outside of model' part, everything is working perfectly

**Comment by ankane** [comment]
Hey @benbonnet, you're missing columns to store the encrypted value and IV. Check the attr_encrypted docs for how to set it up.

**Comment by benbonnet** [comment]
thx a lot! works like a charm
