### ISSUE TITLE
Update context for persisted record

### ISSUE THREAD

**Issue by brovikov** [ankane/kms_encrypted#15]
Hey, thanks for great gem and cool articles about encryption and rails security!

I have a problem - on some stage I need change type of AR model (it's STI model)
But once type changed - it changes the context `model_name` which fails decryption for persisted record. 

Any idea how I can resolve that?

**Comment by ankane** [comment]
Hey @brovikov, you can override the encryption context for a model with:

```ruby
class User < ApplicationRecord
  def kms_encryption_context
    {
      model_name: "OldModelName",
      model_id: id
    }
  end
end
```

If you prefer to update the name, you can use [Easy Rotation](https://github.com/ankane/kms_encrypted/blob/master/guides/Easy-Rotation.md) to change the context.
