### ISSUE TITLE
KMS from GCP - Cannot decrypt data

### ISSUE THREAD

**Issue by ddi-wtag** [ankane/kms_encrypted#16]
Hi there,

I have been following the setup described [in the GCP guide](https://github.com/ankane/kms_encrypted/blob/master/guides/Google.md#google-cloud-kms), and I have the following problem:

Data can be encrypted without an issue (`Model.last.encrypted_field` is set, where `field` is the name of my ActiveRecord attribute), but whenever I try to retrieve that data using `Model.last.field`, I get the following error:

```ruby
Traceback (most recent call last):
        1: from (irb):109
Google::Apis::ClientError (Invalid request)
```

The IAM role in GCP is set to both Decrypt/Encrypt, so that should work.

I passed the credentials from my GCP service account to the `GOOGLE_APPLICATION_CREDENTIALS` environment variable (that wasn't directly specified in the guide, but I assumed that it was the way to go?)

Thanks a lot for your help!

**Comment by ankane** [comment]
Hey @ddi-wtag, I'm not sure what that error indicates. I just ran the tests with the latest google-api-client (0.30.4) and everything passes.

**Comment by ddi-wtag** [comment]
Thanks for your reply @ankane.

Two follow-up questions for you then:

1. Is there a debug mode that we could activate that would not catch the exception coming from `google-api-client` and would display the stacktrace of it? It would be helpful to diagnose the issue further.

2. Could you please tell me where is the configuration for these tests? I have the feeling that there is a configuration issue on my side...If appropriate, I'll extend the documentation in a PR to make things clearer.

Thanks!

**Comment by ankane** [comment]
1. As far as I can tell, it shouldn't be rescuing that exception, but if it is, you can fork and comment out the `rescue` code.
2. There's no special configuration - the google-api-client reads the configuration from the machine/environment.

**Comment by ddi-wtag** [comment]
Thanks for your reply. I'll investigate some more, and I'll post my findings in here.

**Comment by ddi-wtag** [comment]
No particular findings, apart that it works fine now 😆.

For the next ones looking at this issue:

```shell
# Set the two following environment variables
GOOGLE_APPLICATION_CREDENTIALS=<key-of-your-gcp-sa-that-can-access-kms-service>.json
KMS_KEY_ID=<key_id_that_should_start_with_projects>
```

Thanks!
