### ISSUE TITLE
Dont we need AWS Customer managed key(key_id) for decryption?

### ISSUE THREAD

**Issue by sushant12** [ankane/kms_encrypted#17]
I am not sure why we are not using AWS Customer managed key(key_id) to decrypt the data. Am i missing something? https://github.com/ankane/kms_encrypted/blob/master/lib/kms_encrypted/clients/aws.rb#L21

**Comment by veekram** [comment]
@ankane I am curious too :)

**Comment by ankane** [comment]
The ciphertext contains the key id.

**Comment by sushant12** [comment]
@ankane ok. so lets say  there are data in my db that were already encrypted. And I decide to use a new AWS KMS key in my app. Should I be able to decrypt the previously encrypted data?

Right now I can decrypt the data even if use an invalid kms key

**Comment by ankane** [comment]
If your application still has permission to decrypt, then it can decrypt. You can change permissions if this isn’t desired. This is how AWS KMS works.
