### ISSUE TITLE
Using within gcloud cloud build

### ISSUE THREAD

**Issue by benbonnet** [ankane/kms_encrypted#18]
Hello;

We'd need to use kms [in that context](https://cloud.google.com/cloud-build/docs/access-private-github-repos)

I was wondering if and how it would be possible to use the encrypted key stored in the database by the gem; or if there was a method to get a working copy of the stored key

Basically what needs to work is the following :

```
gcloud kms decrypt --ciphertext-file=id_rsa.enc --plaintext-file=/root/.ssh/id_rsa --location=global --keyring=my-keyring --key=github-key
```

(so the idea is to write to `id_rsa.enc` from what has been stored by `kms_encrypted` to have this command working. So far doing so keeps failing - kms complains about invalid ciphertext, for now we're using the ruby kms client)

Hope I'm clear about the need, thanks if any info about that

**Comment by ankane** [comment]
Hey @benbonnet, I'm not sure I fully understand, but it sounds like it's outside the context of database/file upload encryption, so it's probably better to use the Google API client directly.

**Comment by benbonnet** [comment]
Hello;

here's the piece of code : 

```
# setup
client = ::Google::Cloud::Kms::V1::KeyManagementServiceClient.new
encrypter = ::Google::Cloud::Kms::V1::KeyManagementServiceClient.crypto_key_path(
  gcloud_project_id,
  'global',
  kms_key_ring,
  kms_crypto_key
)

# encrypt
kms_client.encrypt(kms_encrypter, plain_value_to_be_encrypted).ciphertext
```
the result is the same using the rest api.

I don't really mean something go wrong in the gem, was more trying to understand the difference. If i may ask, why/how the value stored in `encrypted_` column is not the same as what the `gcloud encrypt ...` command would return ?
