### ISSUE TITLE
SystemStackError when `has_kms_key` follows `mount_uploader`

### ISSUE THREAD

**Issue by bendb-instacart** [ankane/kms_encrypted#19]
Both CarrierWave and kms_encrypted intercept the ActiveRecord `reload` method.  When `has_kms_key` comes after a `mount_uploader` call, the two gems interact in such a way that their `reload` intercepts mutually recurse infinitely, bouncing between the two following callsites:

https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L95

https://github.com/ankane/kms_encrypted/blob/master/lib/kms_encrypted/model.rb#L62

I'm not enough of a rubyist to be able to say which gem is more right than the other; any ideas on how we might fix this?

**Comment by ankane** [comment]
Hey @bendb-instacart, thanks for reporting! Changed how the method is patched on master. Can you give it a shot?

**Comment by bendb-instacart** [comment]
Hi there - thanks for the quick response!  Testing with the master branch now; everything looks good with your fix.  Much appreciated!

**Comment by ankane** [comment]
Great, thanks for confirming!
