### ISSUE TITLE
Add more controls over key generation

### ISSUE THREAD

**Issue by khelal** [ankane/kms_encrypted#2]
Is there a way to control how keys are generated and used? In our case, we don't want to have a key per record, as the costs would be too high, but rather a key per user.

**Comment by ankane** [comment]
Hey @khelal, that shouldn't be too hard. You can do:

```ruby
class User < ApplicationRecord
  has_kms_key
end

class Entry < ApplicationRecord
  belongs_to :user

  attr_encrypted :some_field, key: :user_kms_key

  def user_kms_key
    user.kms_key
  end
end
```
