### ISSUE TITLE
When hybrid algo. is in use by Lockbox, AWS KMS does nothing

### ISSUE THREAD

**Issue by xBartu** [ankane/kms_encrypted#21]
Hey,

We need to use KMS with RSA algorithm, or, other  hybrid algorithm. AWS KMS does nothing. I assume this is a bug or the documentation is not enough.

Is that supported or did I miss something?

Many thanks for your awesome work!

**Comment by ankane** [comment]
Hey @xBartu, KMS Encrypted only works with symmetric keys. You should get an error with Lockbox if you try to pass both `key` and `encryption_key` to the model. What's your model look like?

**Comment by xBartu** [comment]
@ankane yeap, I got the error. I tried combinations :) Thanks for the answer.
