### ISSUE TITLE
OpenSSL::Cipher::CipherError ()

### ISSUE THREAD

**Issue by brovikov** [ankane/kms_encrypted#22]
Hi!

I need help with debug and fix an issue. I have encrypted email field  with:  
```
kms_encrypted (1.1.1) 
aws-sdk-kms (1.30.0)
```
For some reason I'm getting `OpenSSL::Cipher::CipherError ()` when I'm trying read/update this user.
eg in console I'm getting following response:
```
2.6.6 :077 > User.find(92).email
D, [2020-07-13T14:50:42.806427 #16183] DEBUG -- :   User Load (2.2ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."id" = $1 LIMIT $2  [["id", 92], ["LIMIT", 1]]
D, [2020-07-13T14:50:43.004020 #16183] DEBUG -- :   Decrypt Data Key (196.3ms)  Context: {:model_name=>"User", :model_id=>92}
Traceback (most recent call last):
        2: from (irb):77
        1: from (irb):77:in `rescue in irb_binding'
OpenSSL::Cipher::CipherError ()
``` 
So this user is not accessible any more and I couldn't neither update email field nor rotate the key. 

Any idea how I could fix this of force update/rotate email field?

I have email encrypted as following:
```
has_kms_key name: :email, key_id: ENV["EMAIL_KEY_ID"]
attr_encrypted :email, key: :kms_key_email
blind_index :email, key: [ENV["EMAIL_BLIND_INDEX_KEY"]].pack("H*"), expression: ->(v) { v.downcase }, legacy: true
```
For all other persisted users works good. For new created ones as well all is good. Also I have first_name and last_name encrypted. And those fields also works good even for that particular failed user. Only email fails.

Thank you!

**Comment by ankane** [comment]
Hey @brovikov, `OpenSSL::Cipher::CipherError` is the error attr_encrypted returns when decryption fails. For that record, it seems like the KMS data key is different from the key used to encrypt the data. You should be able to update it with:

```ruby
user.encrypted_email = nil
user.encrypted_email_iv = nil
user.encrypted_kms_key = nil
user.email = "new@example.org"
user.save!
```

**Comment by brovikov** [comment]
Thanks a lot for fast response! It works me! User successfully updated.
