### ISSUE TITLE
KmsEncrypted::Database#decrypt missing the version parameter, causing false KmsEncrypted::Error, "Version not active:" error

### ISSUE THREAD

**Issue by robins35** [ankane/kms_encrypted#24]
I am using kms_encrypted (1.2.0), with google-api-client (0.45.0). I added a second key in my google KMS cryptoKey, to transition from version 1 to version 2 (both versions are enabled, with version 2 being the primary). I'm using it to encrypt a few columns on my ChatMessage model, this is how I've configured it on the class:

```
class ChatMessage < ApplicationRecord
  has_kms_key  version: 2,
    previous_versions: {
      1 => { key_id: ENV["KMS_KEY_ID"] }
    }
```

However, I noticed that when I encrypted a new ChatMessage record, and then tried to decrypt it, I always got this error: `KmsEncrypted::Error: Version not active: 2`.  After digging into the gem code, I found the KmsEncrypted::Box#version_key_id method, and that the error was due to a version mismatch:

```
 56     def version_key_id(version)
 57       key_id =
 58         if previous_versions[version]
 59           previous_versions[version][:key_id]
 60         elsif self.version == version
 61           self.key_id
 62         else
 63           raise KmsEncrypted::Error, "Version not active: #{version}"
 64         end
 65
 66       raise ArgumentError, "Missing key id" unless key_id
 67
 68       key_id
 69     end
```

The version of the ciphertext being passed to KmsEncrypted::Box#decrypt was 2 (which is correct, I checked the ciphertext on my record), however the version of the ciphertext that the KmsEncrypted::Box object was instantiated with was 1. This is a record that I had just created/encrypted, it had a v2 ciphertext/encrypted_kms_key, however when its associated KmsEncrypted::Box object was instantiated, it was being set to version 1. I noticed that the KmsEncrypted::Box object defaulted the version to 1 when no version is explicitly passed:

```
    def initialize(key_id: nil, version: nil, previous_versions: nil)
      @key_id = key_id || ENV["KMS_KEY_ID"]
      @version = version || 1
      @previous_versions = previous_versions || {}
    end
```

so I assumed this was the issue. The only place in the gem where KmsEncrypted::Box is instantiated is in lib/kms_encrypted/database.rb, in the encrypt and decrypt methods. I looked in there, and noticed that the version parameter was missing from the decrypt method, and was present in the encrypt method, which makes sense because encryption was working (and setting the proper ciphertext), only decryption failed. Here in KmsEncrypted::Database you can see what I mean:

```
 33     def encrypt(plaintext)
 34       context = context(version)
 35
 36       KmsEncrypted::Box.new(
 37         key_id: key_id,
 38         version: version,
 39         previous_versions: previous_versions
 40       ).encrypt(plaintext, context: context)
 41     end
 42
 43     def decrypt(ciphertext)
 44       # determine version for context
 45       m = /\Av(\d+):/.match(ciphertext)
 46       version = m ? m[1].to_i : 1
 47       context = (options[:upgrade_context] && !m) ? {} : context(version)
 48
 49       KmsEncrypted::Box.new(
 50         key_id: key_id,
 51         previous_versions: previous_versions
 52       ).decrypt(ciphertext, context: context)
 53     end
```

The version is determined on line 46, however the variable is never used, and so the KmsEncrypted::Box is instantiated without a version and defaults to version 1, which then triggers the `KmsEncrypted::Error: Version not active: 2` error.

I forked the gem, and passed the version to the instantiated KmsEncrypted::Box inside KmsEncrypted::Database#decrypt, and that solved the issue for me. I'm able to encrypt new records with version 2, and I'm able to decrypt both version 2 records and the old version 1 records. This is what the new decrypt method looks like:

```
 43     def decrypt(ciphertext)
 44       # determine version for context
 45       m = /\Av(\d+):/.match(ciphertext)
 46       version = m ? m[1].to_i : 1
 47       context = (options[:upgrade_context] && !m) ? {} : context(version)
 48
 49       KmsEncrypted::Box.new(
 50         key_id: key_id,
 51         version: version,
 52         previous_versions: previous_versions
 53       ).decrypt(ciphertext, context: context)
 54     end
```

I made a pull request [here](https://github.com/ankane/kms_encrypted/pull/23). Let me know if I'm mistaken, and this is failing for some other reason, but I am fairly confident that the version is missing and that is causing the error and preventing decryption from happening when working with more than 1 key version.

**Comment by ankane** [comment]
#23 is merged and will be released shortly 🎉
