### ISSUE TITLE
How can encryption/decryption work be shared between separate apps?

### ISSUE THREAD

**Issue by mbtrusona** [ankane/kms_encrypted#26]
Hello,

I am building a service that persists a model with a secure key in the database which I am encrypting using `kms_encrypted`. Another service in my domain will retrieve this sensitive data via an api endpoint. Of course, the consuming service will need to be able to decrypt the secure key. Would you be able to point to an example of this type where one application encrypts and a separate application decrypts?

**Comment by ankane** [comment]
Hey @mbtrusona, if both services use Active Record, you can use the same model code.

```ruby
class User < ApplicationRecord
  has_kms_key
  encrypts :secure_key, key: :kms_key
end
```

Then use different sets of KMS credentials for each service (for instance, use a different IAM user on AWS). Give one set of credentials the ability to encrypt and the other the ability to decrypt.

**Comment by mbtrusona** [comment]
Hi @ankane, thank you for your response. I was hoping that would be the best strategy. One follow-up question: If the decrypt app does not use a database, could the decryption be performed using a class that inherits from ActiveModel instead?

**Comment by ankane** [comment]
To decrypt outside Active Record, use:

```ruby
kms = KmsEncrypted::Box.new
data_encryption_key = kms.decrypt(encrypted_kms_key, context: {model_name: "User", model_id: 123})
```

And then pass the data encryption key to your encryption library. If it's Lockbox:

```ruby
lockbox = Lockbox.new(data_encryption_key, encode: true)
lockbox.decrypt(ciphertext)
```

**Comment by mbtrusona** [comment]
Thanks!
