### ISSUE TITLE
doppler.com

### ISSUE THREAD

**Issue by cj** [ankane/kms_encrypted#27]
Hi,

Would you be interested in a pull request if I created doppler.com client?

Cheers!

**Comment by ankane** [comment]
Hey @cj, thanks for the interest in adding it! I'm hesitant to add more services right now, but let me know if you decide to fork and add it. fwiw, I don't see encrypt/decrypt endpoints in the API docs, so I'm not sure it'll work for this pattern.

**Comment by ankane** [comment]
Cleaning up issues
