### ISSUE TITLE
Retries?

### ISSUE THREAD

**Issue by jakehow** [ankane/kms_encrypted#28]
Hi @ankane 

We see a decent amount of `Seahorse::Client::NetworkingError` with `execution expired` in our application.  It looks like you have max_retries set to 1 on the KMS client.

Any thoughts about making that user configurable or reason why you went with not retrying KMS requests?

**Comment by ankane** [comment]
Hey @jakehow, retries are limited to avoid keeping database transactions open for too long. You should be able to configure it with:

```ruby
KmsEncrypted.aws_client = Aws::KMS::Client.new(retry_limit: 3, http_open_timeout: 2, http_read_timeout: 2)
```

**Comment by jakehow** [comment]
Thanks! Will try this.
