### ISSUE TITLE
Idea: Support Rails.application.credentials for key_id

### ISSUE THREAD

**Issue by Sumukh** [ankane/kms_encrypted#29]
Or possibly allow Procs/methods for the key-id

**Comment by ankane** [comment]
Hey @Sumukh, can you give more context / explain the use case?

**Comment by Sumukh** [comment]
Sure. Sorry for the sparse issue. 

Instead of setting an environment variable for the KMS key, I'd like to manage that within `Rails.application.credentials`

This could handled similarly to how Lockbox handles the `master_key` 

```
Lockbox.master_key = Rails.application.credentials.lockbox[:master_key]
``` 

We could either add `attr_writer :key_id` to `KmsEncrypted`  or `KmsEncrypted::Client`. Happy to throw a PR your way if that sounds reasonable. 

--- 

For the procs/method ID: 

The use case is we want to have different keys for different records. 

```

**Comment by ankane** [comment]
Hey @Sumukh, makes sense. Happy to review a PR. Let's add the method on `KmsEncrypted`.

For procs, I believe it's already supported looking at the code and tests:

```ruby
class User < ApplicationRecord
  has_kms_key key_id: -> { customer_kms_key }
end
```
