### ISSUE TITLE
POST request sent on user forms

### ISSUE THREAD

**Issue by almnes** [ankane/kms_encrypted#3]
When using KMS encrypted the `kms_encryption_context` method is called when a new User instance is created by a form.

If I visit the User sign up form, KMS will run and send a POST request as such:
`Generate Data Key (143.9ms)  Context: {"Record"=>"User/29"}`

I guess it does this because User is being initialized, but it's making things quite buggy for me. Is there a way to fix this?

**Comment by ankane** [comment]
Hey @almnes, thanks for reporting 👍 I submitted a PR to attr_encrypted with a fix.

**Comment by ankane** [comment]
In the meantime, you can use my fork or add `value: ""` to your inputs so the field isn't accessed.

**Comment by almnes** [comment]
Amazing, and highly appreciated! Thanks @ankane

**Comment by ankane** [comment]
Just fyi, the PR was just merged into attr_encrypted, so can switch back to that if using the fork
