### ISSUE TITLE
Using uuid as the primary key in postgresql and eager_encrypt: :fetch_id results in a bad query

### ISSUE THREAD

**Issue by mchristen** [ankane/kms_encrypted#32]
https://github.com/ankane/kms_encrypted/blob/c6eb535293ee64b9b7c369c65c15b3b22528bb27/lib/kms_encrypted/model.rb#L85

In my case `sequence_name` was returning an empty string so the query was `select nextval('')`.

I changed that line as a quick hack to the following and it seemed to work, but I'm not sure if this is the right way of solving the problem. 
```
if self.class.type_for_attribute(:id).type == :uuid
    self.id ||= self.class.connection.execute("select gen_random_uuid() as nextval").first["nextval"]
else
    self.id ||= self.class.connection.execute("select nextval('#{self.class.sequence_name}')").first["nextval"]
end
```

**Comment by ankane** [comment]
Hey @mchristen, that approach should work, or to save a database call, you could use `SecureRandom.uuid` to generate an id. Feel free to submit a PR for the latter approach.
