### ISSUE TITLE
Moving from 'just' lockbox to lockbox+kms_encrypted

### ISSUE THREAD

**Issue by nealharris** [ankane/kms_encrypted#40]
We're currently using lockbox to encrypt database records, but our key is not stored in a KMS. We'd like to migrate to having our key in a KMS. Now, I know that lockbox supports using multiple keys at once, and that kms_encrypted supports multiple kms keys at once, but it's not clear to me if there's a way to use lockbox and kms_encrypted such that some -- but not all -- keys are in a kms. Is this a supported configuration?

**Comment by ankane** [comment]
Hey @nealharris, I'm not sure I fully understand the question, but going off the title, to move a field to KMS Encrypted, you should be able to update your model to:

```ruby
class User < ApplicationRecord
  has_kms_key
  has_encrypted :email, key: :kms_key, previous_versions: [{master_key: Lockbox.master_key}]
end
```

And then follow the rest of the Lockbox key rotation docs.

**Comment by nealharris** [comment]
That does answer my question! I just tested this in dev, and it works swimmingly. Thanks for the help.
