### ISSUE TITLE
Feature Request - Add option to have `encrypt_kms_key` as a `before_save` callback

### ISSUE THREAD

**Issue by jomey** [ankane/kms_encrypted#42]
## Context
I want to prevent double writing with new records to update the encrypted kms key. For that, I am using a different unique attribute (e.g. UUID) that won't change instead of the primary ID. This would be useful when creating a lot of records at once.

However, changing the encryption context to a different column still causes two writes (create + key update). 

Looking at the source did not reveal an easy way to change the `after_save` to a `before_save`.

## Suggestion:
* Add an option to `has_kms_key` to define the callback type (defaults to the current).
* Break up the `encrypt_kms_key` method into updating the key attribute and persisting to the DB. Latter would only be called if this is an `after_save`

**Comment by ankane** [comment]
Hey @jomey, thanks for the suggestion, but I'm having a little trouble following. Can you share the relevant parts of the current model and insert code, as well as what it might look like after the suggested changes?

**Comment by jomey** [comment]
This is how I roughly imagined this (typing it out without having tested this prototype)

In a model using the kms key:
```ruby
class MyModel
  has_kms_key callback_method: :before_save
   
  def kms_encryption_context
    {
       model_name: model_name.to_s,
       model_id: uuid
    }
  end
end
```

## Changes to the [model.rb](https://github.com/ankane/kms_encrypted/blob/master/lib/kms_encrypted/model.rb)
```ruby
module KmsEncrypted
  module Model
    def has_kms_key(name: nil, key_id: nil, eager_encrypt: false, version: 1, previous_versions: nil, upgrade_context: false, callback_method: :after_save)
      ...
      class_eval do
        send(callback_method, :encrypted_kms_key)

        def encrypt_kms_keys
          updates = {}
          self.class.kms_keys.each do |key_method, key|
            instance_var = "@#{key_method}"
            key_column = "encrypted_#{key_method}"
            plaintext_key = instance_variable_get(instance_var)

            if !send(key_column) && plaintext_key
              encrypted_key = KmsEncrypted::Database.new(self, key_method).encrypt(plaintext_key)
              if kms_callback_method == :after_save
                updates[key_column] = encrypted_key
              else
                send(key_column) = encrypted_key
              end
            end
          end
          update_kms_column
        end
      
        def update_kms_column
          if updates.any?
            current_time = current_time_from_proper_timezone
              timestamp_attributes_for_update_in_model.each do |attr|
                updates[attr] = current_time
              end
              update_columns(updates)
            end
          end
        end
        ...
      end
      ...
    end
  end
end
```

To my understanding of the current code, this should help to save the encrypted kms key upon record creation with the first save and remove the need for a callback in cases where the primary ID is not used in the context.

Does this help @ankane?
