### ISSUE TITLE
Use kms_encrypted for development

### ISSUE THREAD

**Issue by GRoguelon** [ankane/kms_encrypted#5]
Hi,

I'm wondering if there is any specific way to have the gem `kms_encrypted` available for development environment without rely on a cloud provider. The idea is to have `kms_encrypted` in production or custom environment like staging with AS or Google and something without AWS or Google in development?

Regards.

**Comment by ankane** [comment]
I'd recommend maintaining dev/prod parity (with different keys), but check out the testing section of the readme for what you're looking for: https://github.com/ankane/kms_encrypted/blob/master/guides/Amazon.md#testing
