### ISSUE TITLE
Upgrading to v1 causes lost of encryption key

### ISSUE THREAD

**Issue by atitan** [ankane/kms_encrypted#9]
Hi,

We're experiencing decryption issue after upgrade kms_encrypted to v1.0.0.

We have a DB model called `Statement` and use ActiveType as extension for virtual attributes.
```Ruby
class Statement
  has_kms_key
  attr_encrypted :pan, key: :kms_key
end

class StatementProduction < ActiveType::Record[Statement]
  attribute :credit_card_number, :string

  before_create :set_pan

  def set_pan
    self.pan = credit_card_number
  end
end

StatementProduction.create(credit_card_number: '12345678')
```

Prior to v1.0.0 everything worked fine. After upgrading, creating db record still works, but failed decrypting `pan` attribute with error message `
OpenSSL::Cipher::CipherError`.

We found that `encrypted_kms_key` was not set in the database and `kms_encrypted` did not send out any request to Google KMS during entire record creation.

I think maybe something is wrong with the kms encryption callback.

**Comment by ankane** [comment]
Hey @atitan, thanks for reporting 👍 I haven't used ActiveType, but many of the internals changed with the 1.0 release. I'd try forking the gem to debug why `encrypted_kms_key` isn't being set.

**Comment by atitan** [comment]
The execution callback `after_save :encrypt_kms_keys` registered successfully on both Class.

After digging a while, found the root cause was `self.class.kms_keys`.

ActiveType uses `Class.new(klass)` to create a new class object which does not have kms_keys.

```Ruby
Statement.kms_keys
=> {:kms_key=>
  {:key_id=>"projects/.......", :name=>nil, :version=>1, :previous_versions=>nil, :upgrade_context=>false}}

StatementProduction.kms_keys
=> {}
```

**Comment by ankane** [comment]
Try the `kms_key_inheritance` branch to see if that fixes it.

**Comment by atitan** [comment]
KMS request was made and `encrypted_kms_key` was set.

But now `encrypted_pan` was missing from the `INSERT` SQL command.

```Ruby
StatementProduction.kms_keys
=> {:kms_key=>
  {:key_id=>"projects...", :name=>nil, :version=>1, :previous_versions=>nil, :upgrade_context=>false}}

q = StatementProduction.new
=> #<StatementProduction created_at: nil, credit_card_number: nil, encrypted_kms_key: nil, encrypted_pan: nil, encrypted_pan_iv: nil, id: nil, name: nil, pan: nil, updated_at: nil>

q.name = 'q'
q.pan = '12353'

q
=> #<StatementProduction created_at: nil, credit_card_number: nil, encrypted_kms_key: nil, encrypted_pan: "vEdYmj745STI+YNdFQtym/eEzWs5\n", encrypted_pan_iv: "UGHd9Ua/GIW/iWJ0\n", id: nil, name: "q", pan: nil, updated_at: nil>

q.save
=> StatementProduction Create (0.5ms)  INSERT INTO "statements" ("name", "encrypted_pan_iv", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["name", "q"], ["encrypted_pan_iv", "UGHd9Ua/GIW/iWJ0\n"], ["created_at", "2019-01-17 10:22:35.057330"], ["updated_at", "2019-01-17 10:22:35.057330"]]
Sending HTTP post https://cloud.kms.googleapis.com......
StatementProduction Update (0.2ms)  UPDATE "statements" SET "encrypted_kms_key" = ?, "updated_at" = ? WHERE "statements"."id" = ?  [["encrypted_kms_key", "v1:CiQAx/cU5..."], ["updated_at", "2019-01-17 10:22:36.059107"], ["id", 13]]

q
=> #<StatementProduction created_at: "2019-01-17 10:22:35", credit_card_number: nil, encrypted_kms_key: "v1:CiQAx/cU5UCq8wpuB...", encrypted_pan: nil, encrypted_pan_iv: "UGHd9Ua/GIW/iWJ0\n", id: 13, name: "q", pan: nil, updated_at: "2019-01-17 10:22:36">
```

**Comment by atitan** [comment]
Sorry, my bad. 😂

Forgot the `set_pan` is replacing `pan` with `credit_card_number` upon creation.

Now it works as intended. Thank you.

**Comment by ankane** [comment]
Great, it's been merged to master and going to delete the branch. Thanks for helping get to the bottom of this 💯
